### ISSUE TITLE
Completely empty module

### ISSUE THREAD

**Issue by gregrebholz** [ramseymcgrath/puppet-remove-hugepage#1]
The manfiests/init.pp from the Puppet Forge download (https://forgeapi.puppetlabs.com/v3/files/ramseymcgrath-remove_hugepage-0.1.1.tar.gz?_ga=1.187839144.1075691272.1435868274) is an empty class.  Perhaps the wrong version was uploaded to the forge?

**Comment by ramseymcgrath** [comment]
You're exactly right, I've updated the forge with a new tarball. Thanks!
